sudo: required
dist: xenial
language: c

addons:
  apt:
    packages:
      - mingw-w64
      - autopoint
      - check libssl-dev libsystemd-dev libjpeg-dev libglib2.0-dev libgstreamer1.0-dev libluajit-5.1-dev libfreetype6-dev libfontconfig1-dev libfribidi-dev libx11-dev libxext-dev libxrender-dev libgl1-mesa-dev libgif-dev libtiff5-dev libpoppler-dev libpoppler-cpp-dev libspectre-dev libraw-dev librsvg2-dev libudev-dev libmount-dev libdbus-1-dev libpulse-dev libsndfile1-dev libxcursor-dev libxcomposite-dev libxinerama-dev libxrandr-dev libxtst-dev libxss-dev libbullet-dev libgstreamer-plugins-base1.0-dev doxygen

matrix:
  include:
    - compiler: x86_64-w64-mingw32-gcc
      env: ARCH=x86_64
    - compiler: i686-w64-mingw32-gcc
      env: ARCH=i686

before_install:
  - 'chmod +x ./*.sh'
  - ./setup.sh
  - ./link_sources.sh

install:
  - ./build.sh efl_upstream native efl
  - ./build.sh efl_upstream $ARCH efl
  - cp -RL ./cross/$ARCH/upstream_efl ./deploy_$ARCH

after_success:
  - ls -al ./deploy_$ARCH
