sudo: required
dist: xenial
language: c

addons:
  apt:
    packages:
      - mingw-w64
      - gettext

matrix:
  include:
    - compiler: x86_64-w64-mingw32-gcc
      env: ARCH=x86_64
    - compiler: i686-w64-mingw32-gcc
      env: ARCH=i686

before_install:
  - 'chmod +x ./*.sh'
  - ./setup.sh
  - ./link_sources.sh

install:
  - ./build.sh efl_upstream native efl
  - ./build.sh efl_upstream $ARCH efl
  - cp -RL ./cross/$ARCH/upstream_efl ./deploy_$ARCH

after_success:
  - ls -al ./deploy_$ARCH
