sudo: required
dist: trusty
language: c

matrix:
  include:
    - compiler: x86_64-w64-mingw32-gcc
      env: ARCH=x86_64
      addons:
        apt:
          packages:
            - libssl1.0.0
            - mingw-w64 
    - compiler: i586-mingw32msvc-gcc
      env: ARCH=i686
      addons:
        apt:
          packages:
            - libssl1.0.0
            - mingw32

before_install:
  - 'chmod +x ./*.sh'
  - ./setup.sh
  - ./link_sources.sh

script:
  - ./build.sh efl_upstream native efl
  - ./build.sh efl_upstream $ARCH efl
  - cp -RL ./cross/$ARCH/upstream_efl ./deploy_$ARCH

after_success:
  - ls -al ./deploy_$ARCH
