sudo: required
dist: xenial
language: c
if: tag IS blank
cache:
  directories:
    - $HOME/cachedir
    - $HOME/.ccache
    - $HOME/autom4te.cache

addons:
  apt:
    packages:
      - mingw-w64
      - autopoint
      - check libssl-dev libsystemd-dev libjpeg-dev libglib2.0-dev libgstreamer1.0-dev libluajit-5.1-dev libfreetype6-dev libfontconfig1-dev libfribidi-dev libx11-dev libxext-dev libxrender-dev libgl1-mesa-dev libgif-dev libtiff5-dev libpoppler-dev libpoppler-cpp-dev libspectre-dev libraw-dev librsvg2-dev libudev-dev libmount-dev libdbus-1-dev libpulse-dev libsndfile1-dev libxcursor-dev libxcomposite-dev libxinerama-dev libxrandr-dev libxtst-dev libxss-dev libbullet-dev libgstreamer-plugins-base1.0-dev doxygen

matrix:
  include:
    - env: ARCH=x86_64 BIT=64
    - env: ARCH=i686   BIT=32

before_install:
  - 'chmod +x ./*.sh'
  - ./setup.sh
  - ./link_sources.sh

script:
  - ./build.sh efl_upstream native efl
  - ./build.sh efl_upstream $ARCH efl
  - cp -RL /opt/windows_$BIT ./deploy_$ARCH

after_success:
  - zip -r ./windows_$BIT.zip ./deploy_$ARCH
  - ls -hl ./windows_$BIT.zip

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Aleksandr Tihomirov"
  - git config --local user.email "github@zetas.space"
  - git tag "efl-master-$(git --git-dir ./sources/efl_upstream/efl/.git log --format=%H -1)"

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "./windows_$BIT.zip"
  skip_cleanup: true